export const COLOURS = {
  white: "#fff",
  black: "#000",
  green: "#00AC76",
  red: "#C04345",
  blue: "#0043F9",
  backgroundLight: "#F0F0F3",
  backgroundMedium: "#B9B9B9",
  backgroundDark: "#777",
}

export const Items = [
  {
    id: 1,
    category: "product",
    productName: "CADEIRA GAMER PICHAU ORION, BRANCA E PRETA",
    productPrice: 1012,
    description:
      "A Cadeira Gamer Pichau Orion é perfeita para quem quer ter conforto enquanto faz suas tarefas no computador",
    isOff: true,
    offPercentage: 10,
    productImage: require("../database/images/products/chairs/chairwhite01.png"),
    isAvailable: true,
    productImageList: [
      require("../database/images/products/chairs/chairwhite01.png"),
      require("../database/images/products/chairs/chairwhite02.png"),
      require("../database/images/products/chairs/chairwhite03.png"),
      require("../database/images/products/chairs/chairwhite04.png"),
      require("../database/images/products/chairs/chairwhite05.png"),
      require("../database/images/products/chairs/chairwhite06.png"),
    ],
  },
  {
    id: 2,
    category: "product",
    productName: "CADEIRA GAMER MANCER TYR PURPLE EDITION, PRETA E ROXA",
    productPrice: 924,
    description:
      "A Cadeira Gamer Mancer Tyr é perfeita para quem quer ter conforto enquanto faz suas tarefas no computador",
    isOff: false,
    offPercentage: 10,
    productImage: require("../database/images/products/chairs/chairpurple01.png"),
    isAvailable: true,
    productImageList: [
      require("../database/images/products/chairs/chairpurple01.png"),
      require("../database/images/products/chairs/chairpurple02.png"),
      require("../database/images/products/chairs/chairpurple03.png"),
      require("../database/images/products/chairs/chairpurple04.png"),
      require("../database/images/products/chairs/chairpurple05.png"),
      require("../database/images/products/chairs/chairpurple06.png"),
    ],
  },
  {
    id: 3,
    category: "accessory",
    itemType: "chair",
    productName: "APOIO DE PE DT3 OFFICE ERGONOMICO VERMELHO",
    productPrice: 199,
    description:
      "Um excelente apoio de pe para o seu computador, com design moderno e elegante",
    isOff: false,
    offPercentage: 10,
    productImage: require("../database/images/accessories/chairs/footsupport01.png"),
    isAvailable: true,
    productImageList: [
      require("../database/images/accessories/chairs/footsupport01.png"),
      require("../database/images/accessories/chairs/footsupport02.png"),
      require("../database/images/accessories/chairs/footsupport03.png"),
      require("../database/images/accessories/chairs/footsupport04.png"),
      require("../database/images/accessories/chairs/footsupport05.png"),
      require("../database/images/accessories/chairs/footsupport06.png"),
    ],
  },
  {
    id: 4,
    category: "accessory",
    productName: "TAPETE PARA CADEIRA GAMER 1200X990MM",
    productPrice: 299,
    description:
      "Um excelente tapete para a sua cadeira gamer, com design moderno e elegante",
    isOff: true,
    offPercentage: 40,
    productImage: require("../database/images/accessories/chairs/chaircarpet01.png"),
    isAvailable: false,
    productImageList: [
      require("../database/images/accessories/chairs/chaircarpet01.png"),
      require("../database/images/accessories/chairs/chaircarpet02.png"),
      require("../database/images/accessories/chairs/chaircarpet03.png"),
    ],
  },
]
