export const COLOURS = {
  white: "#fff",
  black: "#000",
  green: "#00AC76",
  red: "#C04345",
  blue: "#0043F9",
  backgroundLight: "#F0F0F3",
  backgroundMedium: "#B9B9B9",
  backgroundDark: "#777",
}

export const Items = [
  {
    id: 1,
    category: "product",
    productName: "CADEIRA GAMER PICHAU ORION, BRANCA E PRETA",
    productPrice: 1099,
    description:
      "A Cadeira Gamer Pichau Orion é perfeita para quem quer ter conforto enquanto faz suas tarefas no computador",
    isOff: true,
    offPercentage: 10,
    productImage: require("../assets/products/chairs/chairwhite01.png"),
    isAvailable: true,
    productImageList: [
      require("../assets/products/chairs/chairwhite01.png"),
      require("../assets/products/chairs/chairwhite02.png"),
      require("../assets/products/chairs/chairwhite03.png"),
      require("../assets/products/chairs/chairwhite04.png"),
      require("../assets/products/chairs/chairwhite05.png"),
      require("../assets/products/chairs/chairwhite06.png"),
    ],
  },
  {
    id: 2,
    category: "product",
    productName: "CADEIRA GAMER MANCER TYR PURPLE EDITION, PRETA E ROXA",
    productPrice: 899,
    description:
      "A Cadeira Gamer Mancer Tyr é perfeita para quem quer ter conforto enquanto faz suas tarefas no computador",
    isOff: false,
    offPercentage: 10,
    productImage: require("../assets/products/chairs/chairpurple01.png"),
    isAvailable: true,
    productImageList: [
      require("../assets/products/chairs/chairpurple01.png"),
      require("../assets/products/chairs/chairpurple02.png"),
      require("../assets/products/chairs/chairpurple03.png"),
      require("../assets/products/chairs/chairpurple04.png"),
      require("../assets/products/chairs/chairpurple05.png"),
      require("../assets/products/chairs/chairpurple06.png"),
    ],
  },
  {
    id: 3,
    category: "accessory",
    productName: "APOIO DE PE DT3 OFFICE ERGONOMICO VERMELHO",
    productPrice: 199,
    description:
      "Um excelente apoio de pe para o seu computador, com design moderno e elegante",
    isOff: false,
    offPercentage: 10,
    productImage: require("../assets/accessories/chairs/footsupport01.png"),
    isAvailable: true,
    productImageList: [
      require("../assets/accessories/chairs/footsupport01.png"),
      require("../assets/accessories/chairs/footsupport02.png"),
      require("../assets/accessories/chairs/footsupport03.png"),
      require("../assets/accessories/chairs/footsupport04.png"),
      require("../assets/accessories/chairs/footsupport05.png"),
      require("../assets/accessories/chairs/footsupport06.png"),
    ],
  },
  {
    id: 4,
    category: "accessory",
    productName: "TAPETE PARA CADEIRA GAMER 1200X990MM",
    productPrice: 299,
    description:
      "Um excelente tapete para a sua cadeira gamer, com design moderno e elegante",
    isOff: true,
    offPercentage: 40,
    productImage: require("../assets/accessories/chairs/chaircarpet01.png"),
    isAvailable: false,
    productImageList: [
      require("../assets/accessories/chairs/chaircarpet01.png"),
      require("../assets/accessories/chairs/chaircarpet02.png"),
      require("../assets/accessories/chairs/chaircarpet03.png"),
    ],
  },
  {
    id: 5,
    category: "product",
    productName: "TECLADO MECÂNICO LOGITECH G PRO RGB SWITCH GX BLUE CLICKY",
    productPrice: 499,
    description:
      "Os profissionais pediram, nós ouvimos. Com um design compacto e switches clicky de nível superior, o G PRO é testado pelos melhores profissionais, garantido por torneios e construído para vencer",
    isOff: true,
    offPercentage: 10,
    productImage: require("../assets/products/keyboards/gpro01.png"),
    isAvailable: false,
    productImageList: [
      require("../assets/products/keyboards/gpro01.png"),
      require("../assets/products/keyboards/gpro02.png"),
      require("../assets/products/keyboards/gpro03.png"),
      require("../assets/products/keyboards/gpro04.png"),
      require("../assets/products/keyboards/gpro05.png"),
    ],
  },
  {
    id: 6,
    category: "product",
    productName: "TECLADO MECÂNICO LOGITECH G915 TKL RGB SWITCH BROWN WIRELESS",
    productPrice: 999,
    description:
      "O G915 TKL oferece a mesma combinação vencedora de design sofisticado, tecnologias inovadoras, conjunto de recursos e desempenho que o G915 - agora em um design mais compacto e tenkeyless",
    isOff: false,
    offPercentage: 10,
    productImage: require("../assets/products/keyboards/915tkl01.png"),
    isAvailable: true,
    productImageList: [
      require("../assets/products/keyboards/915tkl01.png"),
      require("../assets/products/keyboards/915tkl02.png"),
      require("../assets/products/keyboards/915tkl03.png"),
      require("../assets/products/keyboards/915tkl04.png"),
      require("../assets/products/keyboards/915tkl05.png"),
      require("../assets/products/keyboards/915tkl06.png"),
    ],
  },
  {
    id: 7,
    category: "accessory",
    productName: "CONJUNTO DE TECLAS RAZER PBT DOUBLESHOT BRANCO",
    productPrice: 199,
    description:
      "Keycaps extras para o seu teclado, com design moderno e elegante",
    isOff: false,
    offPercentage: 10,
    productImage: require("../assets/accessories/keyboards/keycaprazer01.png"),
    isAvailable: true,
    productImageList: [
      require("../assets/accessories/keyboards/keycaprazer01.png"),
      require("../assets/accessories/keyboards/keycaprazer02.png"),
      require("../assets/accessories/keyboards/keycaprazer03.png"),
      require("../assets/accessories/keyboards/keycaprazer04.png"),
    ],
  },
  {
    id: 8,
    category: "accessory",
    productName: "Apoio de Pulso HyperX Wrist Rest para Teclado, 457x88mm",
    productPrice: 99,
    description:
      "Apoio de pulso para o seu teclado, com design moderno e elegante",
    isOff: false,
    offPercentage: 10,
    productImage: require("../assets/accessories/keyboards/palmresthx01.png"),
    isAvailable: true,
    productImageList: [
      require("../assets/accessories/keyboards/palmresthx01.png"),
      require("../assets/accessories/keyboards/palmresthx02.png"),
      require("../assets/accessories/keyboards/palmresthx03.png"),
      require("../assets/accessories/keyboards/palmresthx04.png"),
      require("../assets/accessories/keyboards/palmresthx05.png"),
    ],
  },
  {
    id: 9,
    category: "product",
    productName: "MOUSE GAMER LOGITECH G PRO WIRELESS 25000DPI RGB",
    productPrice: 499,
    description:
      "Projetado por 2 anos com a colaboração direta de mais de 50 profissionais de eSports para trazer a forma, o peso e a sensação perfeitos, o PRO WIRELESS é o mouse feito para quem busca a vitória",
    isOff: true,
    offPercentage: 20,
    productImage: require("../assets/products/mouses/gpro01.png"),
    isAvailable: true,
    productImageList: [
      require("../assets/products/mouses/gpro01.png"),
      require("../assets/products/mouses/gpro02.png"),
      require("../assets/products/mouses/gpro03.png"),
      require("../assets/products/mouses/gpro04.png"),
      require("../assets/products/mouses/gpro05.png"),
    ],
  },
  {
    id: 10,
    category: "product",
    productName: "MOUSE GAMER MANCER CROW, RGB, 12000DPI",
    productPrice: 99,
    description:
      "O Mancer Crow é sua nova arma para uma gameplay mais longa e confortável. Ultraleve, com cabo de máxima flexibilidade. O mouse que pesa apenas 75g permite movimentos mais rápidos, sessões mais longas de jogo, minimizando as lesões causadas por movimentos repetitivos",
    isOff: false,
    offPercentage: 20,
    productImage: require("../assets/products/mouses/mancer01.png"),
    isAvailable: false,
    productImageList: [
      require("../assets/products/mouses/mancer01.png"),
      require("../assets/products/mouses/mancer02.png"),
      require("../assets/products/mouses/mancer03.png"),
      require("../assets/products/mouses/mancer04.png"),
      require("../assets/products/mouses/mancer05.png"),
      require("../assets/products/mouses/mancer06.png"),
    ],
  },
  {
    id: 11,
    category: "accessory",
    productName: "MOUSEPAD GAMER CORSAIR MM200 EXTENDED EDITION 930X300X3MM",
    productPrice: 109,
    description:
      "O MM200 é estável e seguro. Você não pode ter uma superfície de mouse que se movimente no meio de um tiroteio, então nós adicionamos uma base antiderrapante que proporciona amortecimento na medida certa. E ele é feito de borracha natural, por isso não tem um odor químico severo.",
    isOff: false,
    offPercentage: 10,
    productImage: require("../assets/accessories/mouses/corsair01.png"),
    isAvailable: false,
    productImageList: [
      require("../assets/accessories/mouses/corsair01.png"),
      require("../assets/accessories/mouses/corsair02.png"),
      require("../assets/accessories/mouses/corsair03.png"),
    ],
  },
  {
    id: 12,
    category: "accessory",
    productName: "MOUSEPAD GAMER LOGITECH G640 GRANDE 460X400X3MM",
    productPrice: 99,
    description:
      "Mousepad com design moderno e elegante. O G640 é o mousepad mais leve e confortável para jogar com o seu computador. O design é feito de borracha natural, por isso não tem um odor químico severo.",
    isOff: true,
    offPercentage: 50,
    productImage: require("../assets/accessories/mouses/logitech01.png"),
    isAvailable: false,
    productImageList: [
      require("../assets/accessories/mouses/logitech01.png"),
      require("../assets/accessories/mouses/logitech02.png"),
    ],
  },
]
